### ISSUE TITLE
CORS error when clicking on the model radio button

### ISSUE THREAD

**Issue by pfeifferj** [codyhouse/product-builder#2]
I'm having this issue where, when clicking the model radio button, a loading spinner appears and nothing happens afterwards. Errors in Chrome

Console when running locally
`Failed to load file:///D:/product-builder-master/product-builder-master/product-01.html: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

Console when running on a server
`Failed to load resource: the server responded with a status of 400 ()`

Firefox returns something completely different:
`Use of Mutation Events is deprecated. Use MutationObserver instead. jquery-3.3.1.min.js:2:40255 `

**Comment by pfeifferj** [comment]
I figured out it was a path issue + a missing directory

**Comment by theharshgupta** [comment]
Hey @pfeifferj I am still facing this error, can you let me know your solution?

**Comment by pfeifferj** [comment]
Hi @theharshgupta Just make sure all dependencies are available, referenced paths are correct and directory permissions are in order.
